services:
  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:16.4
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: >
      bash -c "cd /code/ && python3 wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:7070"
    volumes:
      - .:/code:cached
    ports:
      - "7070:7070"
    depends_on:
      - postgres
  documentation:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: "python3 -m mkdocs serve"
    volumes:
      - .:/code:cached
    ports:
      - "7071:7071"
