site_name: cooking_auth
site_description: A user authentication microservice for an online cooking forum
repo_url: https://github.com/Filo01/cooking_auth
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Filo01">Filo01</a>.
dev_addr: 0.0.0.0:7071

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
