# Generated by Django 5.1.1 on 2024-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20171227_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_2fa",
            field=models.BooleanField(default=False, verbose_name="2FA enabled"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
