# Generated by Django 5.1.1 on 2024-09-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_has_2fa_alter_user_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(db_index=True, max_length=6, verbose_name="Value"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Time")),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="Error count"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("VALID", "VALID"),
                            ("USED", "USED"),
                            ("INVALID", "INVALID"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        max_length=7,
                        verbose_name="OTP State",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
