# Generated by Django 5.1.1 on 2024-09-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="id",
        ),
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="otp",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
