# Generated by Django 5.1.1 on 2024-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_otp_id_alter_otp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="state",
            field=models.CharField(
                choices=[
                    ("VALID", "VALID"),
                    ("USED", "USED"),
                    ("TOO_MANY_ATTEMPTS", "TOO_MANY_ATTEMPTS"),
                    ("EXPIRED", "EXPIRED"),
                ],
                max_length=17,
                verbose_name="OTP State",
            ),
        ),
    ]
