# Generated by Django 5.1.1 on 2024-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_otp_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="state",
            field=models.CharField(
                choices=[
                    ("VALID", "VALID"),
                    ("USED", "USED"),
                    ("TOO_MANY_ATTEMPTS", "TOO_MANY_ATTEMPTS"),
                    ("EXPIRED", "EXPIRED"),
                    ("GONE", "GONE"),
                ],
                max_length=17,
                verbose_name="OTP State",
            ),
        ),
    ]
